### ISSUE TITLE
Mention installation links

### ISSUE THREAD

**Issue by jidanni** [Baptistou/ScriptFilter#1]
On https://github.com/Baptistou/ScriptFilter
mention https://addons.mozilla.org/en-US/firefox/addon/scriptfilteraddon/ and
<del>https://chrome.google.com/webstore/detail/scriptsafe/oiigbmnaadbkfbmpbfijlflahbdbdgdf</del>
so people can try it with one click.

See, I even linked the wrong script, because I had to search for it.

Oh. There is no chrome version.

**Comment by Baptistou** [comment]
Thank you for your comment. I haven't added the links yet as I'm still waiting for approval of my addon on Opera and I'm testing and preparing the current version for Chrome. All the links will be added with upcoming versions soon.

**Comment by jidanni** [comment]
(I would then add link stubs for each, saying "coming soon".
Else people would Google search for them, instead inadvertently finding
similar named apps, and if not careful, thinking they were yours.)

**Comment by Baptistou** [comment]
Good idea ! I just updated the README file. Thank you again.
