### ISSUE TITLE
how do we turn on by default

### ISSUE THREAD

**Issue by Abenezer** [Baptistou/ScriptFilter#3]
all scripts all allowed if i didnt click the button... i want to enable scriptfilter when i start the browser and keep it enabled for all tabs until i want to disable it

is there a feature that turn on scriptfilter by default and turn of when needed... i dont want to load images and block them... i want to block scripts first.... by the way this should be the default behavior

**Comment by Baptistou** [comment]
Hello Abenezer,

ScriptFilter is a developer oriented addon designed like a blacklist i.e. by default websites are not blocked but you decide which of them should be blocked.
In Options page, you can decide to block all tabs by default by selecting "Apply Mode" > "All open tabs" then switch CSP on. Or you can open the top-right menu and click "Enable CSP in all tabs".

If this does not fit your need, I am also developing a new addon for next year which will contain most features from ScriptFilter, be more all-user oriented and be designed like a whitelist i.e. websites are blocked by default.
If you are interested in such a project, I will keep you informed by the release date, probably january 2019.
